In [3]:
import pandas as pd
print(pd.__version__)

3.0.5

In [4]:
import pandas as pd

s = pd.Series(
    [120, 85, 200, 45],
    index=["ene", "feb", "mar", "abr"],
    name="ventas"
)

print(s["mar"])       # acceso por etiqueta
print(s * 1.21)       # vectorizado: IVA

print(s.mean(), s.max())

200
ene    145.20
feb    102.85
mar    242.00
abr     54.45
Name: ventas, dtype: float64
112.5 200

DATAFRAME

In [5]:
import pandas as pd
import numpy as np

In [6]:
# A) Desde un diccionario de listas

df = pd.DataFrame({
    "producto": ["Laptop", "Monitor", "Teclado"],
    "unidades": [3, 7, 12],
    "precio": [1200.0, 320.0, 95.0]
})

df.head()

  producto  unidades  precio
0   Laptop         3  1200.0
1  Monitor         7   320.0
2  Teclado        12    95.0

In [12]:
# B) Desde una lista de diccionarios (típico de una API JSON)

df2 = pd.DataFrame([
    {"producto": "Laptop", "unidades": 3},
    {"producto": "Monitor", "unidades": 7}
])

df2.head()

  producto  unidades
0   Laptop         3
1  Monitor         7

In [6]:
# C) Desde una lista de listas, indicando las columnas

df3 = pd.DataFrame(
    [["Laptop", 3], ["Monitor", 7]],
    columns=["producto", "unidades"]
)

df3.head()

  producto  unidades
0   Laptop         3
1  Monitor         7

CREACION DE COLUMNAS

In [15]:
df

  producto  unidades  precio
0   Laptop         3  1200.0
1  Monitor         7   320.0
2  Teclado        12    95.0

In [17]:
df.shape

(3, 3)

In [18]:
df["importe"] = df["unidades"] * df["precio"]

print(df.shape)

(3, 4)

In [19]:
df.columns

Index(['producto', 'unidades', 'precio', 'importe'], dtype='str')

In [20]:
print(df.columns.tolist())

['producto', 'unidades', 'precio', 'importe']

In [21]:
df.head()

  producto  unidades  precio  importe
0   Laptop         3  1200.0   3600.0
1  Monitor         7   320.0   2240.0
2  Teclado        12    95.0   1140.0

In [22]:
df["dummy"] = 6

df.head()

  producto  unidades  precio  importe  dummy
0   Laptop         3  1200.0   3600.0      6
1  Monitor         7   320.0   2240.0      6
2  Teclado        12    95.0   1140.0      6

In [7]:
df["dummy2"] = [5, 4, 1]

df.head()

  producto  unidades  precio  dummy2
0   Laptop         3  1200.0       5
1  Monitor         7   320.0       4
2  Teclado        12    95.0       1

In [8]:
# Crea una Series con las temperaturas [21, 24, 19, 27, 30] e índice de lunes a viernes.
temperaturas = pd.Series(
    [21, 24, 19, 27, 30],
    index=["Lunes", "Martes", "Miercoles", "Jueves", "Viernes"]
)

print(temperaturas)

# Muestra la media, el máximo y el día que corresponde al máximo (usa .idxmax()).
print("-"*100)
print("Media: ", temperaturas.mean())
print("Maximo: ", temperaturas.max())
print("Dia maximo: ", temperaturas.idxmax())
print("Dia maximo indice: ", temperaturas.argmax())
print("-"*100)

# Crea un DataFrame con 5 productos: nombre, categoría, stock y precio (inventados).
df = pd.DataFrame(
    {
        "nombre": ["Laptop", "Monitor", "Teclado", "Mouse", "Fuente de poder"],
        "categoria": ["Tecnologia", "Tecnologia", "Tecnologia", "Tecnologia", "Tecnologia"],
        "stock": [3, 7, 12, 1, 0],
        "precio":   [1200.0, 320.0, 95.0, 12.23, 90.8]
    }
)
df.head()

# Añade una columna valor_stock = stock × precio.
df["valor_stock"] = df["stock"] * df["precio"]
df.head()

# Imprime la forma del DataFrame y la lista de nombres de columna.
print(df.shape)

print(df.columns.to_list())

Lunes        21
Martes       24
Miercoles    19
Jueves       27
Viernes      30
dtype: int64
----------------------------------------------------------------------------------------------------
Media:  24.2
Maximo:  30
Dia maximo:  Viernes
Dia maximo indice:  4
----------------------------------------------------------------------------------------------------
(5, 5)
['nombre', 'categoria', 'stock', 'precio', 'valor_stock']

In [25]:
temperaturas.head()

Lunes        21
Martes       24
Miercoles    19
Jueves       27
Viernes      30
dtype: int64

Read CSV

In [11]:
# /Users/marcell/Documents/codigo_by_tecsup/datascience-g8/data/ventas.csv
df = pd.read_csv("../data/ventas.csv")
df.head(n=10)

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130,0.0
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.0
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280,0.0
3,2024-01-02,Centro,Pedro Diaz,Laptop Pro,Tecnologia,10,1200,0.0
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130,0.1
5,2024-01-03,Oeste,Javier Sanz,Escritorio,Mobiliario,2,450,0.0
6,2024-01-03,Norte,Carlos Vega,Silla Ergo,Mobiliario,4,280,0.0
7,2024-01-03,Norte,Sofia Leon,Silla Ergo,Mobiliario,1,280,0.0
8,2024-01-03,Centro,Carlos Vega,Laptop Pro,Tecnologia,1,1200,0.1
9,2024-01-03,Centro,Pedro Diaz,Escritorio,Mobiliario,2,450,0.0

In [12]:
df.shape

(1200, 8)

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   fecha            1200 non-null   str
 1   region           1200 non-null   str
 2   vendedor         1182 non-null   str
 3   producto         1200 non-null   str
 4   categoria        1200 non-null   str
 5   unidades         1200 non-null   int64
 6   precio_unitario  1200 non-null   int64
 7   descuento        1165 non-null   float64
dtypes: float64(1), int64(2), str(5)
memory usage: 75.1 KB

In [14]:
df.describe()

          unidades  precio_unitario    descuento
count  1200.000000      1200.000000  1165.000000
mean      7.275833       387.412500     0.047639
std       4.054024       346.020316     0.056273
min       1.000000        45.000000     0.000000
25%       4.000000       130.000000     0.000000
50%       7.000000       280.000000     0.000000
75%      11.000000       450.000000     0.100000
max      14.000000      1200.000000     0.150000

In [17]:
df.sample(10)

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
316,2024-04-09,Centro,Pedro Diaz,Monitor 27,Tecnologia,13,320,0.00
1054,2024-11-13,Este,Ana Torres,Raton Ergo,Accesorios,8,45,0.00
1007,2024-11-02,Centro,Ana Torres,Laptop Pro,Tecnologia,5,1200,0.10
1096,2024-12-02,Sur,Javier Sanz,Raton Ergo,Accesorios,12,45,0.00
128,2024-02-11,Oeste,Marta Ruiz,Silla Ergo,Mobiliario,4,280,0.00
397,2024-05-02,Sur,Marta Ruiz,Raton Ergo,Accesorios,13,45,0.10
302,2024-04-04,Sur,Ana Torres,Monitor 27,Tecnologia,6,320,0.15
1059,2024-11-17,Sur,Javier Sanz,Silla Ergo,Mobiliario,13,280,0.15
760,2024-08-21,Centro,Marta Ruiz,Auriculares,Accesorios,12,130,0.00
32,2024-01-10,Norte,Elena Mora,Silla Ergo,Mobiliario,10,280,0.00

In [16]:
df.describe(include=object)

C:\Users\SpideGamer\AppData\Local\Temp\ipykernel_32248\3998025828.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include=object)

             fecha region    vendedor    producto   categoria
count         1200   1200        1182        1200        1200
unique         349      5           8           8           3
top     2024-02-21  Norte  Marta Ruiz  Silla Ergo  Tecnologia
freq             9    305         170         177         447

In [30]:
df["producto"]

0       Auriculares
1        Monitor 27
2        Silla Ergo
3        Laptop Pro
4       Auriculares
           ...
1195     Raton Ergo
1196     Laptop Pro
1197     Monitor 27
1198     Monitor 27
1199     Raton Ergo
Name: producto, Length: 1200, dtype: str

In [19]:
df.loc[0:4]

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130,0.0
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.0
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280,0.0
3,2024-01-02,Centro,Pedro Diaz,Laptop Pro,Tecnologia,10,1200,0.0
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130,0.1

In [32]:
df.loc[0:2, ["producto", "unidades"]]

      producto  unidades
0  Auriculares         5
1   Monitor 27        14
2   Silla Ergo         1

In [33]:
df.loc[:, ["producto", "unidades"]]

         producto  unidades
0     Auriculares         5
1      Monitor 27        14
2      Silla Ergo         1
3      Laptop Pro        10
4     Auriculares         2
...           ...       ...
1195   Raton Ergo         4
1196   Laptop Pro        13
1197   Monitor 27         2
1198   Monitor 27         6
1199   Raton Ergo         8

[1200 rows x 2 columns]

In [34]:
df.tail()

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
1195,2024-12-30,Este,Luis Gomez,Raton Ergo,Accesorios,4,45,0.00
1196,2024-12-30,Este,Marta Ruiz,Laptop Pro,Tecnologia,13,1200,0.05
1197,2024-12-31,Oeste,Ana Torres,Monitor 27,Tecnologia,2,320,0.05
1198,2024-12-31,Norte,Ana Torres,Monitor 27,Tecnologia,6,320,0.00
1199,2024-12-31,Norte,Marta Ruiz,Raton Ergo,Accesorios,8,45,0.00

In [35]:
df.iloc[-5:, [3, 5]]

        producto  unidades
1195  Raton Ergo         4
1196  Laptop Pro        13
1197  Monitor 27         2
1198  Monitor 27         6
1199  Raton Ergo         8

In [36]:
df.sort_values("unidades", ascending=False)

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
420,2024-05-14,Este,Javier Sanz,Monitor 27,Tecnologia,14,320,0.10
309,2024-04-07,Norte,Elena Mora,Tablet Air,Tecnologia,14,640,0.05
607,2024-07-07,Centro,Javier Sanz,Auriculares,Accesorios,14,130,0.05
604,2024-07-05,Sur,Elena Mora,Laptop Pro,Tecnologia,14,1200,0.00
601,2024-07-05,Sur,Pedro Diaz,Monitor 27,Tecnologia,14,320,0.05
...,...,...,...,...,...,...,...,...
447,2024-05-23,Oeste,Marta Ruiz,Silla Ergo,Mobiliario,1,280,0.00
7,2024-01-03,Norte,Sofia Leon,Silla Ergo,Mobiliario,1,280,0.00
8,2024-01-03,Centro,Carlos Vega,Laptop Pro,Tecnologia,1,1200,0.10
407,2024-05-06,Este,Elena Mora,Laptop Pro,Tecnologia,1,1200,0.05
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280,0.00

In [37]:
df.nlargest(5, "unidades")

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.0
62,2024-01-21,Este,Elena Mora,Silla Ergo,Mobiliario,14,280,0.0
63,2024-01-21,Este,Pedro Diaz,Silla Ergo,Mobiliario,14,280,0.1
75,2024-01-26,Sur,Luis Gomez,Escritorio,Mobiliario,14,450,0.0
76,2024-01-27,Centro,Javier Sanz,Escritorio,Mobiliario,14,450,0.0

In [38]:
df.nlargest(5,"unidades")

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.0
62,2024-01-21,Este,Elena Mora,Silla Ergo,Mobiliario,14,280,0.0
63,2024-01-21,Este,Pedro Diaz,Silla Ergo,Mobiliario,14,280,0.1
75,2024-01-26,Sur,Luis Gomez,Escritorio,Mobiliario,14,450,0.0
76,2024-01-27,Centro,Javier Sanz,Escritorio,Mobiliario,14,450,0.0